//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IMRResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IMRResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IMRResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi lại.
        /// </summary>
        internal static string Contact_Callback {
            get {
                return ResourceManager.GetString("Contact_Callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người liên hệ.
        /// </summary>
        internal static string Contact_ContactPerson {
            get {
                return ResourceManager.GetString("Contact_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi đánh giá cao câu hỏi của bạn và đánh giá cao đề xuất của bạn. Chúng tôi sẽ liên lạc với bạn nhanh nhất có thể..
        /// </summary>
        internal static string Contact_Description {
            get {
                return ResourceManager.GetString("Contact_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư điện tử.
        /// </summary>
        internal static string Contact_EmailAddress {
            get {
                return ResourceManager.GetString("Contact_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string Contact_Firm {
            get {
                return ResourceManager.GetString("Contact_Firm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dùng thử.
        /// </summary>
        internal static string Contact_FreeTrial {
            get {
                return ResourceManager.GetString("Contact_FreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lời nhắn.
        /// </summary>
        internal static string Contact_Message {
            get {
                return ResourceManager.GetString("Contact_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng sử dụng form để liên hệ với chúng tôi.
        /// </summary>
        internal static string Contact_Please {
            get {
                return ResourceManager.GetString("Contact_Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bưu điện.
        /// </summary>
        internal static string Contact_Postcode {
            get {
                return ResourceManager.GetString("Contact_Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường.
        /// </summary>
        internal static string Contact_Street {
            get {
                return ResourceManager.GetString("Contact_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đề.
        /// </summary>
        internal static string Contact_Subject {
            get {
                return ResourceManager.GetString("Contact_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét lưu trữ.
        /// </summary>
        internal static string Contact_Subject_ArchiveScanning {
            get {
                return ResourceManager.GetString("Contact_Subject_ArchiveScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu thập dữ liệu.
        /// </summary>
        internal static string Contact_Subject_DataAcquisition {
            get {
                return ResourceManager.GetString("Contact_Subject_DataAcquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét vẽ.
        /// </summary>
        internal static string Contact_Subject_DrawingScanning {
            get {
                return ResourceManager.GetString("Contact_Subject_DrawingScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào hóa đơn.
        /// </summary>
        internal static string Contact_Subject_InvoiceDataEntry {
            get {
                return ResourceManager.GetString("Contact_Subject_InvoiceDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ quét khẩu độ dạng film.
        /// </summary>
        internal static string Contact_Subject_MicrofilmApertureCardScanning {
            get {
                return ResourceManager.GetString("Contact_Subject_MicrofilmApertureCardScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string Contact_TelephoneNumber {
            get {
                return ResourceManager.GetString("Contact_TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn.
        /// </summary>
        internal static string Contact_Thanks {
            get {
                return ResourceManager.GetString("Contact_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ IMR.
        /// </summary>
        internal static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/Thành phố.
        /// </summary>
        internal static string Contact_Town {
            get {
                return ResourceManager.GetString("Contact_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trách nhiệm.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất lượng.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn của bạn.
        /// </summary>
        internal static string YourChoice {
            get {
                return ResourceManager.GetString("YourChoice", resourceCulture);
            }
        }
    }
}
